  name: shell commands

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: echo string
          run: echo "hello clever"
        - name: Multiline script
          run:
            node -v
            pwd